/* A recursive-descent parser generated by peg 0.1.19 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 20
#line 1 "times.leg"

#include <stdio.h>

#define LEN_MONTH 16
#define LEN_DAY 3
#define LEN_YEAR 5
#define LEN_TIME 12
#define LEN_TIMEZONE 6

char month[LEN_MONTH] = "";
char day[LEN_DAY] = "";
char year[LEN_YEAR] = "";
char time[LEN_TIME] = "";
char tz[LEN_TIMEZONE] = "";

// Defined below
char *get_month(char *month);
char *get_day(char *month);


#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM_R
#define YYPARSEFROM_R	yyparsefrom_r
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy, int yythunkpos)
{
  int pos;
  for (pos= yythunkpos;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy, 0);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_eof(yycontext *yy); /* 20 */
YY_RULE(int) yy_time_full(yycontext *yy); /* 19 */
YY_RULE(int) yy_time_short(yycontext *yy); /* 18 */
YY_RULE(int) yy_month_numeric(yycontext *yy); /* 17 */
YY_RULE(int) yy_month_short(yycontext *yy); /* 16 */
YY_RULE(int) yy_month_long(yycontext *yy); /* 15 */
YY_RULE(int) yy_year_short(yycontext *yy); /* 14 */
YY_RULE(int) yy_day(yycontext *yy); /* 13 */
YY_RULE(int) yy_month(yycontext *yy); /* 12 */
YY_RULE(int) yy_sep(yycontext *yy); /* 11 */
YY_RULE(int) yy_year(yycontext *yy); /* 10 */
YY_RULE(int) yy_date_iso(yycontext *yy); /* 9 */
YY_RULE(int) yy_date_reverse(yycontext *yy); /* 8 */
YY_RULE(int) yy_date_forward(yycontext *yy); /* 7 */
YY_RULE(int) yy_tz(yycontext *yy); /* 6 */
YY_RULE(int) yy_date_any(yycontext *yy); /* 5 */
YY_RULE(int) yy_ignored(yycontext *yy); /* 4 */
YY_RULE(int) yy_time(yycontext *yy); /* 3 */
YY_RULE(int) yy_date(yycontext *yy); /* 2 */
YY_RULE(int) yy_doc(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_tz(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_tz\n"));
  {
#line 52
   strncpy((char *)(&tz), yytext, LEN_TIMEZONE); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_time(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_time\n"));
  {
#line 47
   strncpy((char *)(&time), yytext, LEN_TIME); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_year_short(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_year_short\n"));
  {
#line 44
   snprintf(year, LEN_YEAR, "20%s", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_year(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_year\n"));
  {
#line 43
   strncpy((char *)(&year), yytext, LEN_YEAR); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_day(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_day\n"));
  {
#line 40
   strncpy((char *)(&day), yytext, LEN_DAY); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_month(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_month\n"));
  {
#line 33
   strncpy((char *)(&month), yytext, LEN_MONTH); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_date(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_date\n"));
  {
#line 23
   printf("%s-%s-%s %s %s\n", year, get_month(month), get_day(day), time, tz); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_eof(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yymatchDot(yy)) goto l2;  goto l1;
  l2:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_time_full(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "time_full"));
  {  int yypos4= yy->__pos, yythunkpos4= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;  goto l5;
  l4:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;
  }
  l5:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  if (!yymatchChar(yy, ':')) goto l3;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  if (!yymatchChar(yy, ':')) goto l3;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "time_full", yy->__buf+yy->__pos));
  return 1;
  l3:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "time_full", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_time_short(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "time_short"));
  {  int yypos7= yy->__pos, yythunkpos7= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l7;  goto l8;
  l7:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;
  }
  l8:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;  if (!yymatchChar(yy, ':')) goto l6;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;
  {  int yypos9= yy->__pos, yythunkpos9= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l9;  goto l6;
  l9:;	  yy->__pos= yypos9; yy->__thunkpos= yythunkpos9;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "time_short", yy->__buf+yy->__pos));
  return 1;
  l6:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "time_short", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_month_numeric(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "month_numeric"));
  {  int yypos11= yy->__pos, yythunkpos11= yy->__thunkpos;  if (!yy_year(yy)) goto l11;  goto l10;
  l11:;	  yy->__pos= yypos11; yy->__thunkpos= yythunkpos11;
  }
  {  int yypos12= yy->__pos, yythunkpos12= yy->__thunkpos;  if (!yymatchString(yy, "12")) goto l13;  goto l12;
  l13:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;  if (!yymatchString(yy, "11")) goto l14;  goto l12;
  l14:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;  if (!yymatchString(yy, "10")) goto l15;  goto l12;
  l15:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos17= yy->__pos, yythunkpos17= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l17;  goto l18;
  l17:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;
  }
  l18:;	  if (!yymatchChar(yy, '1')) goto l16;  goto l12;
  l16:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos20= yy->__pos, yythunkpos20= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l20;  goto l21;
  l20:;	  yy->__pos= yypos20; yy->__thunkpos= yythunkpos20;
  }
  l21:;	  if (!yymatchChar(yy, '2')) goto l19;  goto l12;
  l19:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l23;  goto l24;
  l23:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;
  }
  l24:;	  if (!yymatchChar(yy, '3')) goto l22;  goto l12;
  l22:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l26;  goto l27;
  l26:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;
  }
  l27:;	  if (!yymatchChar(yy, '4')) goto l25;  goto l12;
  l25:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l29;  goto l30;
  l29:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;
  }
  l30:;	  if (!yymatchChar(yy, '5')) goto l28;  goto l12;
  l28:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos32= yy->__pos, yythunkpos32= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l32;  goto l33;
  l32:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;
  }
  l33:;	  if (!yymatchChar(yy, '6')) goto l31;  goto l12;
  l31:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos35= yy->__pos, yythunkpos35= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l35;  goto l36;
  l35:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;
  }
  l36:;	  if (!yymatchChar(yy, '7')) goto l34;  goto l12;
  l34:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos38= yy->__pos, yythunkpos38= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l38;  goto l39;
  l38:;	  yy->__pos= yypos38; yy->__thunkpos= yythunkpos38;
  }
  l39:;	  if (!yymatchChar(yy, '8')) goto l37;  goto l12;
  l37:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos40= yy->__pos, yythunkpos40= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l40;  goto l41;
  l40:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;
  }
  l41:;	  if (!yymatchChar(yy, '9')) goto l10;
  }
  l12:;	
  {  int yypos42= yy->__pos, yythunkpos42= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l42;  goto l10;
  l42:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "month_numeric", yy->__buf+yy->__pos));
  return 1;
  l10:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "month_numeric", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_month_short(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "month_short"));
  {  int yypos44= yy->__pos, yythunkpos44= yy->__thunkpos;  if (!yymatchString(yy, "Jan")) goto l45;  goto l44;
  l45:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Feb")) goto l46;  goto l44;
  l46:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Mar")) goto l47;  goto l44;
  l47:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Apr")) goto l48;  goto l44;
  l48:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "May")) goto l49;  goto l44;
  l49:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Jun")) goto l50;  goto l44;
  l50:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Jul")) goto l51;  goto l44;
  l51:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Aug")) goto l52;  goto l44;
  l52:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Sep")) goto l53;  goto l44;
  l53:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Oct")) goto l54;  goto l44;
  l54:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Nov")) goto l55;  goto l44;
  l55:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yymatchString(yy, "Dec")) goto l43;
  }
  l44:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "month_short", yy->__buf+yy->__pos));
  return 1;
  l43:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "month_short", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_month_long(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "month_long"));
  {  int yypos57= yy->__pos, yythunkpos57= yy->__thunkpos;  if (!yymatchString(yy, "January")) goto l58;  goto l57;
  l58:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "February")) goto l59;  goto l57;
  l59:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "March")) goto l60;  goto l57;
  l60:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "April")) goto l61;  goto l57;
  l61:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "May")) goto l62;  goto l57;
  l62:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "June")) goto l63;  goto l57;
  l63:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "July")) goto l64;  goto l57;
  l64:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "August")) goto l65;  goto l57;
  l65:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "September")) goto l66;  goto l57;
  l66:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "October")) goto l67;  goto l57;
  l67:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "November")) goto l68;  goto l57;
  l68:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yymatchString(yy, "December")) goto l56;
  }
  l57:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "month_long", yy->__buf+yy->__pos));
  return 1;
  l56:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "month_long", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_year_short(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "year_short"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l69;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l69;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l69;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l69;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_year_short, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "year_short", yy->__buf+yy->__pos));
  return 1;
  l69:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "year_short", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_day(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "day"));
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yy_year(yy)) goto l71;  goto l70;
  l71:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;
  }
  {  int yypos72= yy->__pos, yythunkpos72= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l72;  goto l70;
  l72:;	  yy->__pos= yypos72; yy->__thunkpos= yythunkpos72;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l70;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l70;
  {  int yypos73= yy->__pos, yythunkpos73= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l73;  goto l74;
  l73:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;
  }
  l74:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l70;
#undef yytext
#undef yyleng
  }
  {  int yypos75= yy->__pos, yythunkpos75= yy->__thunkpos;
  {  int yypos77= yy->__pos, yythunkpos77= yy->__thunkpos;  if (!yymatchString(yy, "st")) goto l78;  goto l77;
  l78:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;  if (!yymatchString(yy, "nd")) goto l79;  goto l77;
  l79:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;  if (!yymatchString(yy, "rd")) goto l80;  goto l77;
  l80:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;  if (!yymatchString(yy, "th")) goto l75;
  }
  l77:;	  goto l76;
  l75:;	  yy->__pos= yypos75; yy->__thunkpos= yythunkpos75;
  }
  l76:;	
  {  int yypos81= yy->__pos, yythunkpos81= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l81;  goto l70;
  l81:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;
  }  yyDo(yy, yy_1_day, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "day", yy->__buf+yy->__pos));
  return 1;
  l70:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "day", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_month(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "month"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l82;
#undef yytext
#undef yyleng
  }
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yy_month_long(yy)) goto l84;  goto l83;
  l84:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yy_month_short(yy)) goto l85;  goto l83;
  l85:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yy_month_numeric(yy)) goto l82;
  }
  l83:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l82;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_month, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "month", yy->__buf+yy->__pos));
  return 1;
  l82:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "month", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_sep(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "sep"));  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\360\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l86;
  yyprintf((stderr, "  ok   %s @ %s\n", "sep", yy->__buf+yy->__pos));
  return 1;
  l86:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sep", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_year(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "year"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l87;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l87;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l87;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l87;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l87;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l87;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_year, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "year", yy->__buf+yy->__pos));
  return 1;
  l87:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "year", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date_iso(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date_iso"));
  {  int yypos89= yy->__pos, yythunkpos89= yy->__thunkpos;  if (!yy_year(yy)) goto l90;  if (!yymatchChar(yy, '-')) goto l90;  if (!yy_month(yy)) goto l90;  if (!yymatchChar(yy, '-')) goto l90;  if (!yy_day(yy)) goto l90;  if (!yymatchChar(yy, 'T')) goto l90;  if (!yy_time(yy)) goto l90;  goto l89;
  l90:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;  if (!yy_year(yy)) goto l88;  if (!yymatchChar(yy, '-')) goto l88;  if (!yy_month(yy)) goto l88;  if (!yymatchChar(yy, '-')) goto l88;  if (!yy_day(yy)) goto l88;
  }
  l89:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "date_iso", yy->__buf+yy->__pos));
  return 1;
  l88:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date_iso", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date_reverse(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date_reverse"));
  {  int yypos92= yy->__pos, yythunkpos92= yy->__thunkpos;  if (!yy_day(yy)) goto l93;
  l94:;	
  {  int yypos95= yy->__pos, yythunkpos95= yy->__thunkpos;  if (!yy_sep(yy)) goto l95;  goto l94;
  l95:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;
  }  if (!yy_month(yy)) goto l93;
  l96:;	
  {  int yypos97= yy->__pos, yythunkpos97= yy->__thunkpos;  if (!yy_sep(yy)) goto l97;  goto l96;
  l97:;	  yy->__pos= yypos97; yy->__thunkpos= yythunkpos97;
  }  if (!yy_year(yy)) goto l93;  goto l92;
  l93:;	  yy->__pos= yypos92; yy->__thunkpos= yythunkpos92;  if (!yy_day(yy)) goto l98;
  l99:;	
  {  int yypos100= yy->__pos, yythunkpos100= yy->__thunkpos;  if (!yy_sep(yy)) goto l100;  goto l99;
  l100:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;
  }  if (!yy_month(yy)) goto l98;  goto l92;
  l98:;	  yy->__pos= yypos92; yy->__thunkpos= yythunkpos92;  if (!yy_year(yy)) goto l91;
  l101:;	
  {  int yypos102= yy->__pos, yythunkpos102= yy->__thunkpos;  if (!yy_sep(yy)) goto l102;  goto l101;
  l102:;	  yy->__pos= yypos102; yy->__thunkpos= yythunkpos102;
  }  if (!yy_month(yy)) goto l91;
  }
  l92:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "date_reverse", yy->__buf+yy->__pos));
  return 1;
  l91:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date_reverse", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date_forward(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date_forward"));
  {  int yypos104= yy->__pos, yythunkpos104= yy->__thunkpos;  if (!yy_year(yy)) goto l105;  if (!yy_sep(yy)) goto l105;
  l106:;	
  {  int yypos107= yy->__pos, yythunkpos107= yy->__thunkpos;  if (!yy_sep(yy)) goto l107;  goto l106;
  l107:;	  yy->__pos= yypos107; yy->__thunkpos= yythunkpos107;
  }  if (!yy_month(yy)) goto l105;  if (!yy_sep(yy)) goto l105;
  l108:;	
  {  int yypos109= yy->__pos, yythunkpos109= yy->__thunkpos;  if (!yy_sep(yy)) goto l109;  goto l108;
  l109:;	  yy->__pos= yypos109; yy->__thunkpos= yythunkpos109;
  }  if (!yy_day(yy)) goto l105;  goto l104;
  l105:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yy_month(yy)) goto l110;
  l111:;	
  {  int yypos112= yy->__pos, yythunkpos112= yy->__thunkpos;  if (!yy_month(yy)) goto l112;  goto l111;
  l112:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;
  }  if (!yy_sep(yy)) goto l110;
  l113:;	
  {  int yypos114= yy->__pos, yythunkpos114= yy->__thunkpos;  if (!yy_sep(yy)) goto l114;  goto l113;
  l114:;	  yy->__pos= yypos114; yy->__thunkpos= yythunkpos114;
  }  if (!yy_day(yy)) goto l110;  if (!yy_sep(yy)) goto l110;
  l115:;	
  {  int yypos116= yy->__pos, yythunkpos116= yy->__thunkpos;  if (!yy_sep(yy)) goto l116;  goto l115;
  l116:;	  yy->__pos= yypos116; yy->__thunkpos= yythunkpos116;
  }  if (!yy_year(yy)) goto l110;  goto l104;
  l110:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yy_month(yy)) goto l117;  if (!yy_sep(yy)) goto l117;
  l118:;	
  {  int yypos119= yy->__pos, yythunkpos119= yy->__thunkpos;  if (!yy_sep(yy)) goto l119;  goto l118;
  l119:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;
  }  if (!yy_day(yy)) goto l117;  if (!yy_sep(yy)) goto l117;
  l120:;	
  {  int yypos121= yy->__pos, yythunkpos121= yy->__thunkpos;  if (!yy_sep(yy)) goto l121;  goto l120;
  l121:;	  yy->__pos= yypos121; yy->__thunkpos= yythunkpos121;
  }  if (!yy_year_short(yy)) goto l117;  goto l104;
  l117:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yy_month(yy)) goto l122;  if (!yy_sep(yy)) goto l122;
  l123:;	
  {  int yypos124= yy->__pos, yythunkpos124= yy->__thunkpos;  if (!yy_sep(yy)) goto l124;  goto l123;
  l124:;	  yy->__pos= yypos124; yy->__thunkpos= yythunkpos124;
  }  if (!yy_day(yy)) goto l122;  goto l104;
  l122:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yy_month(yy)) goto l103;  if (!yy_sep(yy)) goto l103;
  l125:;	
  {  int yypos126= yy->__pos, yythunkpos126= yy->__thunkpos;  if (!yy_sep(yy)) goto l126;  goto l125;
  l126:;	  yy->__pos= yypos126; yy->__thunkpos= yythunkpos126;
  }  if (!yy_year(yy)) goto l103;
  }
  l104:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "date_forward", yy->__buf+yy->__pos));
  return 1;
  l103:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date_forward", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_tz(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "tz"));
  {  int yypos128= yy->__pos, yythunkpos128= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l129;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, 'Z')) goto l129;  goto l128;
  l129:;	  yy->__pos= yypos128; yy->__thunkpos= yythunkpos128;
  {  int yypos130= yy->__pos, yythunkpos130= yy->__thunkpos;  if (!yymatchChar(yy, '+')) goto l131;  goto l130;
  l131:;	  yy->__pos= yypos130; yy->__thunkpos= yythunkpos130;  if (!yymatchChar(yy, '-')) goto l127;
  }
  l130:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l127;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l127;
  {  int yypos132= yy->__pos, yythunkpos132= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l132;  goto l133;
  l132:;	  yy->__pos= yypos132; yy->__thunkpos= yythunkpos132;
  }
  l133:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l127;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l127;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l127;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_tz, yy->__begin, yy->__end);
  }
  l128:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "tz", yy->__buf+yy->__pos));
  return 1;
  l127:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "tz", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date_any(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date_any"));
  {  int yypos135= yy->__pos, yythunkpos135= yy->__thunkpos;  if (!yy_date_forward(yy)) goto l136;  goto l135;
  l136:;	  yy->__pos= yypos135; yy->__thunkpos= yythunkpos135;  if (!yy_date_reverse(yy)) goto l137;  goto l135;
  l137:;	  yy->__pos= yypos135; yy->__thunkpos= yythunkpos135;  if (!yy_date_iso(yy)) goto l134;
  }
  l135:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "date_any", yy->__buf+yy->__pos));
  return 1;
  l134:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date_any", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ignored(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ignored"));
  {  int yypos139= yy->__pos, yythunkpos139= yy->__thunkpos;  if (!yy_day(yy)) goto l139;  goto l138;
  l139:;	  yy->__pos= yypos139; yy->__thunkpos= yythunkpos139;
  }
  {  int yypos140= yy->__pos, yythunkpos140= yy->__thunkpos;  if (!yy_month(yy)) goto l140;  goto l138;
  l140:;	  yy->__pos= yypos140; yy->__thunkpos= yythunkpos140;
  }
  {  int yypos141= yy->__pos, yythunkpos141= yy->__thunkpos;  if (!yy_year(yy)) goto l141;  goto l138;
  l141:;	  yy->__pos= yypos141; yy->__thunkpos= yythunkpos141;
  }
  {  int yypos142= yy->__pos, yythunkpos142= yy->__thunkpos;  if (!yy_tz(yy)) goto l142;  goto l138;
  l142:;	  yy->__pos= yypos142; yy->__thunkpos= yythunkpos142;
  }
  {  int yypos143= yy->__pos, yythunkpos143= yy->__thunkpos;  if (!yy_time(yy)) goto l143;  goto l138;
  l143:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;
  }  if (!yymatchDot(yy)) goto l138;
  yyprintf((stderr, "  ok   %s @ %s\n", "ignored", yy->__buf+yy->__pos));
  return 1;
  l138:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ignored", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_time(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "time"));
  {  int yypos145= yy->__pos, yythunkpos145= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l146;
#undef yytext
#undef yyleng
  }  if (!yy_time_short(yy)) goto l146;  goto l145;
  l146:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yy_time_full(yy)) goto l144;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l144;
#undef yytext
#undef yyleng
  }
  {  int yypos147= yy->__pos, yythunkpos147= yy->__thunkpos;
  {  int yypos149= yy->__pos, yythunkpos149= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l150;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l150;
  l151:;	
  {  int yypos152= yy->__pos, yythunkpos152= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l152;  goto l151;
  l152:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;
  }  goto l149;
  l150:;	  yy->__pos= yypos149; yy->__thunkpos= yythunkpos149;
  {  int yypos153= yy->__pos, yythunkpos153= yy->__thunkpos;
  l155:;	
  {  int yypos156= yy->__pos, yythunkpos156= yy->__thunkpos;  if (!yy_sep(yy)) goto l156;  goto l155;
  l156:;	  yy->__pos= yypos156; yy->__thunkpos= yythunkpos156;
  }  if (!yymatchString(yy, "AM")) goto l154;  goto l153;
  l154:;	  yy->__pos= yypos153; yy->__thunkpos= yythunkpos153;  if (!yymatchString(yy, "PM")) goto l147;
  }
  l153:;	
  }
  l149:;	  goto l148;
  l147:;	  yy->__pos= yypos147; yy->__thunkpos= yythunkpos147;
  }
  l148:;	  yyDo(yy, yy_1_time, yy->__begin, yy->__end);
  }
  l145:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "time", yy->__buf+yy->__pos));
  return 1;
  l144:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "time", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date"));
  {  int yypos158= yy->__pos, yythunkpos158= yy->__thunkpos;  if (!yy_time(yy)) goto l158;  goto l159;
  l158:;	  yy->__pos= yypos158; yy->__thunkpos= yythunkpos158;
  }
  l159:;	
  l160:;	
  {  int yypos161= yy->__pos, yythunkpos161= yy->__thunkpos;  if (!yy_ignored(yy)) goto l161;  goto l160;
  l161:;	  yy->__pos= yypos161; yy->__thunkpos= yythunkpos161;
  }  if (!yy_date_any(yy)) goto l157;
  l162:;	
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;  if (!yy_ignored(yy)) goto l163;  goto l162;
  l163:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;
  }
  {  int yypos164= yy->__pos, yythunkpos164= yy->__thunkpos;  if (!yy_time(yy)) goto l164;  goto l165;
  l164:;	  yy->__pos= yypos164; yy->__thunkpos= yythunkpos164;
  }
  l165:;	
  {  int yypos166= yy->__pos, yythunkpos166= yy->__thunkpos;  if (!yy_tz(yy)) goto l166;  goto l167;
  l166:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;
  }
  l167:;	  yyDo(yy, yy_1_date, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "date", yy->__buf+yy->__pos));
  return 1;
  l157:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_doc(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "doc"));
  {  int yypos171= yy->__pos, yythunkpos171= yy->__thunkpos;  if (!yy_date(yy)) goto l172;  goto l171;
  l172:;	  yy->__pos= yypos171; yy->__thunkpos= yythunkpos171;  if (!yymatchDot(yy)) goto l168;
  }
  l171:;	
  l169:;	
  {  int yypos170= yy->__pos, yythunkpos170= yy->__thunkpos;
  {  int yypos173= yy->__pos, yythunkpos173= yy->__thunkpos;  if (!yy_date(yy)) goto l174;  goto l173;
  l174:;	  yy->__pos= yypos173; yy->__thunkpos= yythunkpos173;  if (!yymatchDot(yy)) goto l170;
  }
  l173:;	  goto l169;
  l170:;	  yy->__pos= yypos170; yy->__thunkpos= yythunkpos170;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "doc", yy->__buf+yy->__pos));
  return 1;
  l168:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "doc", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM_R(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok, yythunkpos;
  YYSTYPE *yyval;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__val= yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yythunkpos= yyctx->__thunkpos;
  yyval= yyctx->__val;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx, yythunkpos);
  yyctx->__thunkpos= yythunkpos;
  yyctx->__val= yyval;
  return yyok;
}

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= YYPARSEFROM_R(YY_CTX_ARG_ yystart);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_doc);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 61 "times.leg"


// Dictionaries we need to look up month numeric values
char* long_months[] = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
char* short_month[] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
char* int_str[] =     { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" };

// Turn short or long month names or short numeric values into double-digit numeric values
char *get_month(char *month) {
	if (strnlen(month, LEN_MONTH) == 1) {
		int index = atoi(month);
	   	if (index > 12) {
	   		return ""; // Some other weird match
	   	}	
		snprintf(month, LEN_MONTH, "%s", int_str[index-1]);
		return month;
	}
	if (strnlen(month, LEN_MONTH) == 2) {
		return month;
	}
	for (int i = 0; i < 12; i++) {
	    if (strcmp(month, short_month[i]) == 0) {
			return int_str[i];
	    }
	    if (strcmp(month, long_months[i]) == 0) {
			return int_str[i];
	    }
	}
	return month;
}

char *get_day(char *day) {
	if (strnlen(day, LEN_DAY) == 2) {
		return day;
	}
	return int_str[atoi(day)-1];
}

int main() {
	while (yyparse()) {
		month[0] = '\0'; day[0] = '\0'; year[0] = '\0'; time[0] = '\0'; tz[0] = '\0';
	}
	return 0;
}

