/* A recursive-descent parser generated by peg 0.1.19 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 25
#line 1 "times.leg"

#include <stdio.h>

#define LEN_MONTH 16
#define LEN_DAY 3
#define LEN_YEAR 5
#define LEN_TIME 12
#define LEN_TIMEZONE 6

char month[LEN_MONTH] = "";
char day[LEN_DAY] = "";
char year[LEN_YEAR] = "";
char time[LEN_TIME] = "";
char tz[LEN_TIMEZONE] = "";

// Defined below
char *get_month(char *month);
char *get_day(char *month);
char* get_time(char* time);

//#define YY_DEBUG 1

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM_R
#define YYPARSEFROM_R	yyparsefrom_r
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy, int yythunkpos)
{
  int pos;
  for (pos= yythunkpos;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy, 0);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_space(yycontext *yy); /* 25 */
YY_RULE(int) yy_time_full(yycontext *yy); /* 24 */
YY_RULE(int) yy_time_short(yycontext *yy); /* 23 */
YY_RULE(int) yy_month_numeric(yycontext *yy); /* 22 */
YY_RULE(int) yy_month_short(yycontext *yy); /* 21 */
YY_RULE(int) yy_month_long(yycontext *yy); /* 20 */
YY_RULE(int) yy_time_millis(yycontext *yy); /* 19 */
YY_RULE(int) yy_year_short(yycontext *yy); /* 18 */
YY_RULE(int) yy_day(yycontext *yy); /* 17 */
YY_RULE(int) yy_month(yycontext *yy); /* 16 */
YY_RULE(int) yy_sep(yycontext *yy); /* 15 */
YY_RULE(int) yy_year(yycontext *yy); /* 14 */
YY_RULE(int) yy_date_reverse(yycontext *yy); /* 13 */
YY_RULE(int) yy_date_forward(yycontext *yy); /* 12 */
YY_RULE(int) yy_date_iso(yycontext *yy); /* 11 */
YY_RULE(int) yy_tz(yycontext *yy); /* 10 */
YY_RULE(int) yy_date_any(yycontext *yy); /* 9 */
YY_RULE(int) yy_ignored(yycontext *yy); /* 8 */
YY_RULE(int) yy_time(yycontext *yy); /* 7 */
YY_RULE(int) yy_eol(yycontext *yy); /* 6 */
YY_RULE(int) yy_anything(yycontext *yy); /* 5 */
YY_RULE(int) yy_date(yycontext *yy); /* 4 */
YY_RULE(int) yy_eof(yycontext *yy); /* 3 */
YY_RULE(int) yy_line(yycontext *yy); /* 2 */
YY_RULE(int) yy_doc(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_tz(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_tz\n"));
  {
#line 58
   strncpy((char *)(&tz), yytext, LEN_TIMEZONE); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_time(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_time\n"));
  {
#line 52
   strncpy((char *)(&time), yytext, LEN_TIME); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_year_short(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_year_short\n"));
  {
#line 49
   snprintf(year, LEN_YEAR, "20%s", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_year(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_year\n"));
  {
#line 48
   strncpy((char *)(&year), yytext, LEN_YEAR); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_day(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_day\n"));
  {
#line 45
   strncpy((char *)(&day), yytext, LEN_DAY); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_month(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_month\n"));
  {
#line 38
   strncpy((char *)(&month), yytext, LEN_MONTH); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_date(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_date\n"));
  {
#line 27
  
	   																						printf("%s-%s-%s %s %s\n", year, get_month(month), get_day(day), get_time(time), tz);
																							month[0] = '\0'; day[0] = '\0'; year[0] = '\0'; time[0] = '\0'; tz[0] = '\0';
	   																					;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_space(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "space"));  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "space", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "space", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_time_full(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "time_full"));
  {  int yypos3= yy->__pos, yythunkpos3= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  goto l4;
  l3:;	  yy->__pos= yypos3; yy->__thunkpos= yythunkpos3;
  }
  l4:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;  if (!yymatchChar(yy, ':')) goto l2;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;  if (!yymatchChar(yy, ':')) goto l2;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;
  {  int yypos5= yy->__pos, yythunkpos5= yy->__thunkpos;
  {  int yypos6= yy->__pos, yythunkpos6= yy->__thunkpos;
  {  int yypos8= yy->__pos, yythunkpos8= yy->__thunkpos;  if (!yy_time_millis(yy)) goto l9;  goto l8;
  l9:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;
  {  int yypos10= yy->__pos, yythunkpos10= yy->__thunkpos;
  l12:;	
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yy_space(yy)) goto l13;  goto l12;
  l13:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;
  }  if (!yymatchString(yy, "AM")) goto l11;  goto l10;
  l11:;	  yy->__pos= yypos10; yy->__thunkpos= yythunkpos10;  if (!yymatchString(yy, "PM")) goto l6;
  }
  l10:;	
  }
  l8:;	  goto l7;
  l6:;	  yy->__pos= yypos6; yy->__thunkpos= yythunkpos6;
  }
  l7:;	  yy->__pos= yypos5; yy->__thunkpos= yythunkpos5;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "time_full", yy->__buf+yy->__pos));
  return 1;
  l2:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "time_full", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_time_short(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "time_short"));
  {  int yypos15= yy->__pos, yythunkpos15= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l15;  goto l16;
  l15:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;
  }
  l16:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l14;  if (!yymatchChar(yy, ':')) goto l14;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l14;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l14;
  {  int yypos17= yy->__pos, yythunkpos17= yy->__thunkpos;  if (!yy_space(yy)) goto l14;  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;
  }
  {  int yypos18= yy->__pos, yythunkpos18= yy->__thunkpos;
  {  int yypos20= yy->__pos, yythunkpos20= yy->__thunkpos;  if (!yymatchString(yy, "AM")) goto l21;  goto l20;
  l21:;	  yy->__pos= yypos20; yy->__thunkpos= yythunkpos20;  if (!yymatchString(yy, "PM")) goto l18;
  }
  l20:;	  goto l19;
  l18:;	  yy->__pos= yypos18; yy->__thunkpos= yythunkpos18;
  }
  l19:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "time_short", yy->__buf+yy->__pos));
  return 1;
  l14:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "time_short", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_month_numeric(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "month_numeric"));
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yy_year(yy)) goto l23;  goto l22;
  l23:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;
  }
  {  int yypos24= yy->__pos, yythunkpos24= yy->__thunkpos;  if (!yymatchString(yy, "12")) goto l25;  goto l24;
  l25:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;  if (!yymatchString(yy, "11")) goto l26;  goto l24;
  l26:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;  if (!yymatchString(yy, "10")) goto l27;  goto l24;
  l27:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l29;  goto l30;
  l29:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;
  }
  l30:;	  if (!yymatchChar(yy, '1')) goto l28;  goto l24;
  l28:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos32= yy->__pos, yythunkpos32= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l32;  goto l33;
  l32:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;
  }
  l33:;	  if (!yymatchChar(yy, '2')) goto l31;  goto l24;
  l31:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos35= yy->__pos, yythunkpos35= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l35;  goto l36;
  l35:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;
  }
  l36:;	  if (!yymatchChar(yy, '3')) goto l34;  goto l24;
  l34:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos38= yy->__pos, yythunkpos38= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l38;  goto l39;
  l38:;	  yy->__pos= yypos38; yy->__thunkpos= yythunkpos38;
  }
  l39:;	  if (!yymatchChar(yy, '4')) goto l37;  goto l24;
  l37:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos41= yy->__pos, yythunkpos41= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l41;  goto l42;
  l41:;	  yy->__pos= yypos41; yy->__thunkpos= yythunkpos41;
  }
  l42:;	  if (!yymatchChar(yy, '5')) goto l40;  goto l24;
  l40:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos44= yy->__pos, yythunkpos44= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l44;  goto l45;
  l44:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;
  }
  l45:;	  if (!yymatchChar(yy, '6')) goto l43;  goto l24;
  l43:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos47= yy->__pos, yythunkpos47= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l47;  goto l48;
  l47:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;
  }
  l48:;	  if (!yymatchChar(yy, '7')) goto l46;  goto l24;
  l46:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos50= yy->__pos, yythunkpos50= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l50;  goto l51;
  l50:;	  yy->__pos= yypos50; yy->__thunkpos= yythunkpos50;
  }
  l51:;	  if (!yymatchChar(yy, '8')) goto l49;  goto l24;
  l49:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos52= yy->__pos, yythunkpos52= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l52;  goto l53;
  l52:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;
  }
  l53:;	  if (!yymatchChar(yy, '9')) goto l22;
  }
  l24:;	
  {  int yypos54= yy->__pos, yythunkpos54= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l54;  goto l22;
  l54:;	  yy->__pos= yypos54; yy->__thunkpos= yythunkpos54;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "month_numeric", yy->__buf+yy->__pos));
  return 1;
  l22:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "month_numeric", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_month_short(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "month_short"));
  {  int yypos56= yy->__pos, yythunkpos56= yy->__thunkpos;  if (!yymatchString(yy, "Jan")) goto l57;  goto l56;
  l57:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Feb")) goto l58;  goto l56;
  l58:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Mar")) goto l59;  goto l56;
  l59:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Apr")) goto l60;  goto l56;
  l60:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "May")) goto l61;  goto l56;
  l61:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Jun")) goto l62;  goto l56;
  l62:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Jul")) goto l63;  goto l56;
  l63:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Aug")) goto l64;  goto l56;
  l64:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Sep")) goto l65;  goto l56;
  l65:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Oct")) goto l66;  goto l56;
  l66:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Nov")) goto l67;  goto l56;
  l67:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "Dec")) goto l55;
  }
  l56:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "month_short", yy->__buf+yy->__pos));
  return 1;
  l55:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "month_short", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_month_long(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "month_long"));
  {  int yypos69= yy->__pos, yythunkpos69= yy->__thunkpos;  if (!yymatchString(yy, "January")) goto l70;  goto l69;
  l70:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "February")) goto l71;  goto l69;
  l71:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "March")) goto l72;  goto l69;
  l72:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "April")) goto l73;  goto l69;
  l73:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "May")) goto l74;  goto l69;
  l74:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "June")) goto l75;  goto l69;
  l75:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "July")) goto l76;  goto l69;
  l76:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "August")) goto l77;  goto l69;
  l77:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "September")) goto l78;  goto l69;
  l78:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "October")) goto l79;  goto l69;
  l79:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "November")) goto l80;  goto l69;
  l80:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;  if (!yymatchString(yy, "December")) goto l68;
  }
  l69:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "month_long", yy->__buf+yy->__pos));
  return 1;
  l68:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "month_long", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_time_millis(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "time_millis"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l81;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l81;
  l82:;	
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l83;  goto l82;
  l83:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "time_millis", yy->__buf+yy->__pos));
  return 1;
  l81:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "time_millis", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_year_short(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "year_short"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l84;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l84;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l84;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l84;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_year_short, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "year_short", yy->__buf+yy->__pos));
  return 1;
  l84:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "year_short", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_day(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "day"));
  {  int yypos86= yy->__pos, yythunkpos86= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l86;  goto l85;
  l86:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l85;
#undef yytext
#undef yyleng
  }
  {  int yypos87= yy->__pos, yythunkpos87= yy->__thunkpos;  if (!yymatchString(yy, "31")) goto l88;  goto l87;
  l88:;	  yy->__pos= yypos87; yy->__thunkpos= yythunkpos87;  if (!yymatchString(yy, "30")) goto l89;  goto l87;
  l89:;	  yy->__pos= yypos87; yy->__thunkpos= yythunkpos87;
  {  int yypos90= yy->__pos, yythunkpos90= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l90;  goto l91;
  l90:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;
  }
  l91:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l85;
  }
  l87:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l85;
#undef yytext
#undef yyleng
  }
  {  int yypos92= yy->__pos, yythunkpos92= yy->__thunkpos;
  {  int yypos94= yy->__pos, yythunkpos94= yy->__thunkpos;  if (!yymatchString(yy, "st")) goto l95;  goto l94;
  l95:;	  yy->__pos= yypos94; yy->__thunkpos= yythunkpos94;  if (!yymatchString(yy, "nd")) goto l96;  goto l94;
  l96:;	  yy->__pos= yypos94; yy->__thunkpos= yythunkpos94;  if (!yymatchString(yy, "rd")) goto l97;  goto l94;
  l97:;	  yy->__pos= yypos94; yy->__thunkpos= yythunkpos94;  if (!yymatchString(yy, "th")) goto l92;
  }
  l94:;	  goto l93;
  l92:;	  yy->__pos= yypos92; yy->__thunkpos= yythunkpos92;
  }
  l93:;	
  {  int yypos98= yy->__pos, yythunkpos98= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l98;  goto l85;
  l98:;	  yy->__pos= yypos98; yy->__thunkpos= yythunkpos98;
  }  yyDo(yy, yy_1_day, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "day", yy->__buf+yy->__pos));
  return 1;
  l85:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "day", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_month(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "month"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l99;
#undef yytext
#undef yyleng
  }
  {  int yypos100= yy->__pos, yythunkpos100= yy->__thunkpos;  if (!yy_month_long(yy)) goto l101;  goto l100;
  l101:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;  if (!yy_month_short(yy)) goto l102;  goto l100;
  l102:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;  if (!yy_month_numeric(yy)) goto l99;
  }
  l100:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l99;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_month, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "month", yy->__buf+yy->__pos));
  return 1;
  l99:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "month", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_sep(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "sep"));  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\360\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l103;
  yyprintf((stderr, "  ok   %s @ %s\n", "sep", yy->__buf+yy->__pos));
  return 1;
  l103:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sep", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_year(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "year"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l104;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l104;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l104;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l104;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l104;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l104;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_year, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "year", yy->__buf+yy->__pos));
  return 1;
  l104:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "year", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date_reverse(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date_reverse"));
  {  int yypos106= yy->__pos, yythunkpos106= yy->__thunkpos;  if (!yy_day(yy)) goto l107;
  l108:;	
  {  int yypos109= yy->__pos, yythunkpos109= yy->__thunkpos;  if (!yy_sep(yy)) goto l109;  goto l108;
  l109:;	  yy->__pos= yypos109; yy->__thunkpos= yythunkpos109;
  }  if (!yy_month(yy)) goto l107;
  l110:;	
  {  int yypos111= yy->__pos, yythunkpos111= yy->__thunkpos;  if (!yy_sep(yy)) goto l111;  goto l110;
  l111:;	  yy->__pos= yypos111; yy->__thunkpos= yythunkpos111;
  }  if (!yy_year(yy)) goto l107;  goto l106;
  l107:;	  yy->__pos= yypos106; yy->__thunkpos= yythunkpos106;  if (!yy_day(yy)) goto l112;
  l113:;	
  {  int yypos114= yy->__pos, yythunkpos114= yy->__thunkpos;  if (!yy_sep(yy)) goto l114;  goto l113;
  l114:;	  yy->__pos= yypos114; yy->__thunkpos= yythunkpos114;
  }  if (!yy_month(yy)) goto l112;  goto l106;
  l112:;	  yy->__pos= yypos106; yy->__thunkpos= yythunkpos106;  if (!yy_year(yy)) goto l105;
  l115:;	
  {  int yypos116= yy->__pos, yythunkpos116= yy->__thunkpos;  if (!yy_sep(yy)) goto l116;  goto l115;
  l116:;	  yy->__pos= yypos116; yy->__thunkpos= yythunkpos116;
  }  if (!yy_month(yy)) goto l105;
  }
  l106:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "date_reverse", yy->__buf+yy->__pos));
  return 1;
  l105:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date_reverse", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date_forward(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date_forward"));
  {  int yypos118= yy->__pos, yythunkpos118= yy->__thunkpos;  if (!yy_year(yy)) goto l119;  if (!yy_sep(yy)) goto l119;
  l120:;	
  {  int yypos121= yy->__pos, yythunkpos121= yy->__thunkpos;  if (!yy_sep(yy)) goto l121;  goto l120;
  l121:;	  yy->__pos= yypos121; yy->__thunkpos= yythunkpos121;
  }  if (!yy_month(yy)) goto l119;  if (!yy_sep(yy)) goto l119;
  l122:;	
  {  int yypos123= yy->__pos, yythunkpos123= yy->__thunkpos;  if (!yy_sep(yy)) goto l123;  goto l122;
  l123:;	  yy->__pos= yypos123; yy->__thunkpos= yythunkpos123;
  }  if (!yy_day(yy)) goto l119;  goto l118;
  l119:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_month(yy)) goto l124;
  l125:;	
  {  int yypos126= yy->__pos, yythunkpos126= yy->__thunkpos;  if (!yy_month(yy)) goto l126;  goto l125;
  l126:;	  yy->__pos= yypos126; yy->__thunkpos= yythunkpos126;
  }  if (!yy_sep(yy)) goto l124;
  l127:;	
  {  int yypos128= yy->__pos, yythunkpos128= yy->__thunkpos;  if (!yy_sep(yy)) goto l128;  goto l127;
  l128:;	  yy->__pos= yypos128; yy->__thunkpos= yythunkpos128;
  }  if (!yy_day(yy)) goto l124;  if (!yy_sep(yy)) goto l124;
  l129:;	
  {  int yypos130= yy->__pos, yythunkpos130= yy->__thunkpos;  if (!yy_sep(yy)) goto l130;  goto l129;
  l130:;	  yy->__pos= yypos130; yy->__thunkpos= yythunkpos130;
  }  if (!yy_year(yy)) goto l124;  goto l118;
  l124:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_month(yy)) goto l131;  if (!yy_sep(yy)) goto l131;
  l132:;	
  {  int yypos133= yy->__pos, yythunkpos133= yy->__thunkpos;  if (!yy_sep(yy)) goto l133;  goto l132;
  l133:;	  yy->__pos= yypos133; yy->__thunkpos= yythunkpos133;
  }  if (!yy_day(yy)) goto l131;  if (!yy_sep(yy)) goto l131;
  l134:;	
  {  int yypos135= yy->__pos, yythunkpos135= yy->__thunkpos;  if (!yy_sep(yy)) goto l135;  goto l134;
  l135:;	  yy->__pos= yypos135; yy->__thunkpos= yythunkpos135;
  }  if (!yy_year_short(yy)) goto l131;  goto l118;
  l131:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_month(yy)) goto l136;  if (!yy_sep(yy)) goto l136;
  l137:;	
  {  int yypos138= yy->__pos, yythunkpos138= yy->__thunkpos;  if (!yy_sep(yy)) goto l138;  goto l137;
  l138:;	  yy->__pos= yypos138; yy->__thunkpos= yythunkpos138;
  }  if (!yy_day(yy)) goto l136;  goto l118;
  l136:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_month(yy)) goto l117;  if (!yy_sep(yy)) goto l117;
  l139:;	
  {  int yypos140= yy->__pos, yythunkpos140= yy->__thunkpos;  if (!yy_sep(yy)) goto l140;  goto l139;
  l140:;	  yy->__pos= yypos140; yy->__thunkpos= yythunkpos140;
  }  if (!yy_year(yy)) goto l117;
  }
  l118:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "date_forward", yy->__buf+yy->__pos));
  return 1;
  l117:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date_forward", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date_iso(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date_iso"));
  {  int yypos142= yy->__pos, yythunkpos142= yy->__thunkpos;  if (!yy_year(yy)) goto l143;  if (!yymatchChar(yy, '-')) goto l143;  if (!yy_month(yy)) goto l143;  if (!yymatchChar(yy, '-')) goto l143;  if (!yy_day(yy)) goto l143;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\001\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l143;  if (!yy_time(yy)) goto l143;
  {  int yypos144= yy->__pos, yythunkpos144= yy->__thunkpos;  if (!yy_time_millis(yy)) goto l144;  goto l145;
  l144:;	  yy->__pos= yypos144; yy->__thunkpos= yythunkpos144;
  }
  l145:;	  if (!yy_tz(yy)) goto l143;  goto l142;
  l143:;	  yy->__pos= yypos142; yy->__thunkpos= yythunkpos142;  if (!yy_year(yy)) goto l141;  if (!yymatchChar(yy, '-')) goto l141;  if (!yy_month(yy)) goto l141;  if (!yymatchChar(yy, '-')) goto l141;  if (!yy_day(yy)) goto l141;
  }
  l142:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "date_iso", yy->__buf+yy->__pos));
  return 1;
  l141:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date_iso", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_tz(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "tz"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l146;
#undef yytext
#undef yyleng
  }
  {  int yypos147= yy->__pos, yythunkpos147= yy->__thunkpos;  if (!yymatchChar(yy, 'Z')) goto l148;  goto l147;
  l148:;	  yy->__pos= yypos147; yy->__thunkpos= yythunkpos147;
  {  int yypos149= yy->__pos, yythunkpos149= yy->__thunkpos;  if (!yymatchChar(yy, '+')) goto l150;  goto l149;
  l150:;	  yy->__pos= yypos149; yy->__thunkpos= yythunkpos149;  if (!yymatchChar(yy, '-')) goto l146;
  }
  l149:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l146;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l146;
  {  int yypos151= yy->__pos, yythunkpos151= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l151;  goto l152;
  l151:;	  yy->__pos= yypos151; yy->__thunkpos= yythunkpos151;
  }
  l152:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l146;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l146;
  }
  l147:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l146;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_tz, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "tz", yy->__buf+yy->__pos));
  return 1;
  l146:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "tz", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date_any(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date_any"));
  {  int yypos154= yy->__pos, yythunkpos154= yy->__thunkpos;  if (!yy_date_iso(yy)) goto l155;  goto l154;
  l155:;	  yy->__pos= yypos154; yy->__thunkpos= yythunkpos154;  if (!yy_date_forward(yy)) goto l156;  goto l154;
  l156:;	  yy->__pos= yypos154; yy->__thunkpos= yythunkpos154;  if (!yy_date_reverse(yy)) goto l153;
  }
  l154:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "date_any", yy->__buf+yy->__pos));
  return 1;
  l153:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date_any", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ignored(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ignored"));
  {  int yypos158= yy->__pos, yythunkpos158= yy->__thunkpos;  if (!yy_space(yy)) goto l159;  goto l158;
  l159:;	  yy->__pos= yypos158; yy->__thunkpos= yythunkpos158;
  {  int yypos160= yy->__pos, yythunkpos160= yy->__thunkpos;  if (!yy_day(yy)) goto l160;  goto l157;
  l160:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;
  }
  {  int yypos161= yy->__pos, yythunkpos161= yy->__thunkpos;  if (!yy_month(yy)) goto l161;  goto l157;
  l161:;	  yy->__pos= yypos161; yy->__thunkpos= yythunkpos161;
  }
  {  int yypos162= yy->__pos, yythunkpos162= yy->__thunkpos;  if (!yy_year(yy)) goto l162;  goto l157;
  l162:;	  yy->__pos= yypos162; yy->__thunkpos= yythunkpos162;
  }
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;  if (!yy_tz(yy)) goto l163;  goto l157;
  l163:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;
  }
  {  int yypos164= yy->__pos, yythunkpos164= yy->__thunkpos;  if (!yy_time(yy)) goto l164;  goto l157;
  l164:;	  yy->__pos= yypos164; yy->__thunkpos= yythunkpos164;
  }
  {  int yypos165= yy->__pos, yythunkpos165= yy->__thunkpos;  if (!yy_eol(yy)) goto l165;  goto l157;
  l165:;	  yy->__pos= yypos165; yy->__thunkpos= yythunkpos165;
  }  if (!yymatchDot(yy)) goto l157;
  }
  l158:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ignored", yy->__buf+yy->__pos));
  return 1;
  l157:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ignored", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_time(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "time"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l166;
#undef yytext
#undef yyleng
  }
  {  int yypos167= yy->__pos, yythunkpos167= yy->__thunkpos;  if (!yy_time_short(yy)) goto l168;  goto l167;
  l168:;	  yy->__pos= yypos167; yy->__thunkpos= yythunkpos167;  if (!yy_time_full(yy)) goto l166;
  }
  l167:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l166;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_time, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "time", yy->__buf+yy->__pos));
  return 1;
  l166:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "time", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_eol(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eol"));
  {  int yypos170= yy->__pos, yythunkpos170= yy->__thunkpos;  if (!yymatchChar(yy, '\n')) goto l171;  goto l170;
  l171:;	  yy->__pos= yypos170; yy->__thunkpos= yythunkpos170;  if (!yymatchString(yy, "\r\n")) goto l172;  goto l170;
  l172:;	  yy->__pos= yypos170; yy->__thunkpos= yythunkpos170;  if (!yymatchString(yy, "\n\r")) goto l169;
  }
  l170:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 1;
  l169:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_anything(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "anything"));
  {  int yypos174= yy->__pos, yythunkpos174= yy->__thunkpos;  if (!yy_eol(yy)) goto l174;  goto l173;
  l174:;	  yy->__pos= yypos174; yy->__thunkpos= yythunkpos174;
  }  if (!yymatchDot(yy)) goto l173;
  yyprintf((stderr, "  ok   %s @ %s\n", "anything", yy->__buf+yy->__pos));
  return 1;
  l173:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "anything", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_date(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "date"));
  {  int yypos176= yy->__pos, yythunkpos176= yy->__thunkpos;  if (!yy_time(yy)) goto l176;  goto l177;
  l176:;	  yy->__pos= yypos176; yy->__thunkpos= yythunkpos176;
  }
  l177:;	
  l178:;	
  {  int yypos179= yy->__pos, yythunkpos179= yy->__thunkpos;  if (!yy_ignored(yy)) goto l179;  goto l178;
  l179:;	  yy->__pos= yypos179; yy->__thunkpos= yythunkpos179;
  }  if (!yy_date_any(yy)) goto l175;
  l180:;	
  {  int yypos181= yy->__pos, yythunkpos181= yy->__thunkpos;  if (!yy_ignored(yy)) goto l181;  goto l180;
  l181:;	  yy->__pos= yypos181; yy->__thunkpos= yythunkpos181;
  }
  {  int yypos182= yy->__pos, yythunkpos182= yy->__thunkpos;  if (!yy_time(yy)) goto l182;  goto l183;
  l182:;	  yy->__pos= yypos182; yy->__thunkpos= yythunkpos182;
  }
  l183:;	
  l184:;	
  {  int yypos185= yy->__pos, yythunkpos185= yy->__thunkpos;  if (!yy_ignored(yy)) goto l185;  goto l184;
  l185:;	  yy->__pos= yypos185; yy->__thunkpos= yythunkpos185;
  }
  {  int yypos186= yy->__pos, yythunkpos186= yy->__thunkpos;  if (!yy_tz(yy)) goto l186;  goto l187;
  l186:;	  yy->__pos= yypos186; yy->__thunkpos= yythunkpos186;
  }
  l187:;	  yyDo(yy, yy_1_date, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "date", yy->__buf+yy->__pos));
  return 1;
  l175:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "date", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_eof(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos189= yy->__pos, yythunkpos189= yy->__thunkpos;  if (!yymatchDot(yy)) goto l189;  goto l188;
  l189:;	  yy->__pos= yypos189; yy->__thunkpos= yythunkpos189;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yy->__buf+yy->__pos));
  return 1;
  l188:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_line(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "line"));
  l191:;	
  {  int yypos192= yy->__pos, yythunkpos192= yy->__thunkpos;
  {  int yypos193= yy->__pos, yythunkpos193= yy->__thunkpos;  if (!yy_date(yy)) goto l194;  goto l193;
  l194:;	  yy->__pos= yypos193; yy->__thunkpos= yythunkpos193;  if (!yy_anything(yy)) goto l192;
  }
  l193:;	  goto l191;
  l192:;	  yy->__pos= yypos192; yy->__thunkpos= yythunkpos192;
  }  if (!yy_eol(yy)) goto l190;
  yyprintf((stderr, "  ok   %s @ %s\n", "line", yy->__buf+yy->__pos));
  return 1;
  l190:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "line", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_doc(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "doc"));  if (!yy_line(yy)) goto l195;
  l196:;	
  {  int yypos197= yy->__pos, yythunkpos197= yy->__thunkpos;  if (!yy_line(yy)) goto l197;  goto l196;
  l197:;	  yy->__pos= yypos197; yy->__thunkpos= yythunkpos197;
  }  if (!yy_eof(yy)) goto l195;
  yyprintf((stderr, "  ok   %s @ %s\n", "doc", yy->__buf+yy->__pos));
  return 1;
  l195:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "doc", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM_R(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok, yythunkpos;
  YYSTYPE *yyval;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__val= yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yythunkpos= yyctx->__thunkpos;
  yyval= yyctx->__val;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx, yythunkpos);
  yyctx->__thunkpos= yythunkpos;
  yyctx->__val= yyval;
  return yyok;
}

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= YYPARSEFROM_R(YY_CTX_ARG_ yystart);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_doc);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 68 "times.leg"


// Dictionaries we need to look up month numeric values
char* long_months[] = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
char* short_month[] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
char* int_str[] =     { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" };

// Turn short or long month names or short numeric values into double-digit numeric values
char *get_month(char *month) {
	if (strnlen(month, LEN_MONTH) == 1) {
		int index = atoi(month);
	   	if (index > 12) {
	   		return ""; // Some other weird match
	   	}	
		snprintf(month, LEN_MONTH, "%s", int_str[index-1]);
		return month;
	}
	if (strnlen(month, LEN_MONTH) == 2) {
		return month;
	}
	for (int i = 0; i < 12; i++) {
	    if (strcmp(month, short_month[i]) == 0) {
			return int_str[i];
	    }
	    if (strcmp(month, long_months[i]) == 0) {
			return int_str[i];
	    }
	}
	return month;
}

char *get_day(char *day) {
	if (strnlen(day, LEN_DAY) == 2) {
		return day;
	}
	return int_str[atoi(day)-1];
}

char* get_time(char* time) {
	char *formatted[LEN_TIME];
    int hours = 0, minutes = 0, seconds = 0;
    int part = 0; // 0: hours, 1: minutes, 2: seconds
    int temp_value = 0;

    if (strnlen(time, LEN_TIME) == 0) {
        return time;
    }

    for (int i = 0; time[i] != '\0'; i++) {
        if (time[i] >= '0' && time[i] <= '9') { // Check if the character is a number
            // Accumulate the number
            temp_value = temp_value * 10 + (time[i] - '0');
        } else if (time[i] == ':') {
            // Assign the accumulated number to the corresponding part
            if (part == 0) {
                hours = temp_value;
            } else if (part == 1) {
                minutes = temp_value;
            }
            part++;
            temp_value = 0; // Reset temp_value for the next part
        } else {
            return time;
        }
    }

    // Assign the last accumulated value to the appropriate part
    if (part == 0) {
        hours = temp_value;
    } else if (part == 1) {
        minutes = temp_value;
    } else if (part == 2) {
        seconds = temp_value;
    }

    // Format the output string
    snprintf((char *)formatted, LEN_TIME, "%02d:%02d:%02d", hours, minutes, seconds);
	memcpy(time, formatted, LEN_TIME);
    return time;
}

int main() {
	while (yyparse()) {
		month[0] = '\0'; day[0] = '\0'; year[0] = '\0'; time[0] = '\0'; tz[0] = '\0';
	}
	return 0;
}

